Define github-hostname for trusted teams
gardener/cc-utils pull request #1069
Opened 2024-11-04 09:53 UTC by zkdev

Useful for scenarios where trusted-teams from multiple github instances have to be considered.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2024-11-04 09:53 UTC, zkdev commented
/hold

do not merge (yet), requires cfg changes

2024-11-04 15:28 UTC, ccwienk requested changes

2024-11-04 15:28 UTC, ccwienk commented on model/concourse.py
> +    teams: list[str]
list is mutable. declaring the dataclass as frozen is inconsistent w/ that. suggestion: declare the class as mutable (non-frozen)

2024-11-04 15:28 UTC, ccwienk commented on model/concourse.py
> +            dacite.from_dict(
can we keep this simpler and just keep a list of strings? it should be fairly simple to discriminate between qualified and non-qualified teams, as github does not allow `/` (or `.` for that matter) characters in team-names.

Hence, entries of the form `foo/bar` (two parts if splitting by `/`) should be safe to translate to `<org>/<teamname>`, whereas entries of the form `host.tld/foo/bar` (three parts if splitting by `/`) should be safe to interpret as qualified

2024-11-05 14:24 UTC, zkdev commented
merge with https://github.com/gardener/cc-utils/pull/1070 , let's follow-up there

2024-11-05 14:24 UTC, closed without merging