move uploading of component descriptor to its own step
gardener/cc-utils pull request #613
Opened 2021-06-15 13:58 UTC by AndreasBurger

**What this PR does / why we need it**:
Moves the upload of component descriptors to a separate step. This prevents issues with CDs being published before the corresponding release has been properly created.

This upload-step is always included for release-jobs, but it can also be configured for jobs containing the component-descriptor trait (to preserve existing functionality, if desired)

2021-06-17 12:24 UTC, ccwienk commented
@AndreasBurger : please fix linter error(s)

2021-06-17 12:24 UTC, ccwienk commented on concourse/model/traits/component_descriptor.py
> +        name='upload_component_descriptor',
please rm this (again)

2021-06-17 12:25 UTC, ccwienk commented on concourse/model/traits/component_descriptor.py
> +    def upload_component_descriptor(self):
also rm

2021-06-17 12:28 UTC, ccwienk commented on concourse/model/traits/component_descriptor.py
>      def ctx_repository(self) -> model.ctx_repository.CtxRepositoryCfg:
how about adding a second attribute `snapshot_ctx_repository` (note: use cfg-element-name, as for this getter). if set, the following semantics applies:

1. component-descriptor-step _always_ uploads to configured (snapshot-)ctx-repository
2. release-trait should do a "promote"; second step can be omitted as a shortcut to get this change done a bit quicker

2021-06-17 12:31 UTC, ccwienk requested changes

2021-06-17 12:31 UTC, ccwienk commented on concourse/model/traits/component_descriptor.py
> +        if pipeline_args.has_trait('release'):
I think this should be done the other way around.

component-descriptor step should upload to snapshot-repo (if available/configured)
however, it should be up to the release-step to react upon the component-descriptor trait's configuration, wdyt?

2021-06-17 12:31 UTC, ccwienk commented on concourse/model/traits/component_descriptor.py
> +            if self.trait.upload_component_descriptor():
why do this in a separate step?

2021-06-18 15:58 UTC, merged

2021-06-18 16:00 UTC, AndreasBurger commented
Implemented the requested/discussed changes:

If configured, both CTF and CDv2 will now be uploaded during the CD-step to the desired ctx-repository. Otherwise, they will _only_ be published during the release-step