CODEOWNER resolving utils
gardener/cc-utils pull request #705
Opened 2022-04-01 10:23 UTC by zkdev

**What this PR does / why we need it**:
Add utils to resolve codeowners not only by email, but an extensible set of attributes.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator

```

2022-04-01 10:58 UTC, ccwienk requested changes

2022-04-01 10:58 UTC, ccwienk commented on github/codeowners.py
> +class CodeOwnerPersonalName:
nit: it is just a PersonalName

2022-04-01 10:58 UTC, ccwienk commented on github/codeowners.py
> +class CodeOwnerGithubUser:
GithubUser

2022-04-01 10:58 UTC, ccwienk commented on github/codeowners.py
> +class CodeOwnerEmail:
EmailAddress

2022-04-01 10:58 UTC, ccwienk commented on github/codeowners.py
> +
define a base class `UserInfo(Base?)` that defines the `source` attr, which is common to all DCs you defined in this diff

2022-04-01 10:58 UTC, ccwienk commented on github/codeowners.py
> +class CodeOwner:
that's not exactly how I imagined this :-/

also, I think this code actually belongs into the delivery-service repository

I would like to have a more abstract object representing a UserIdentity (maybe call it like this?)

A UserIdentity consists of a non-empty collection of (typed) UserInfo objects:
- email-address
- github-user
- personal-name
- ... (for now, there are no more, but there might be. e.g. "d-user")

2022-04-01 10:58 UTC, ccwienk commented on github/codeowners.py
> +    def create(
as mentioned above, this should be a sequence..

2022-04-01 10:58 UTC, ccwienk commented on github/codeowners.py
> +        if isinstance(attribute, CodeOwnerGithubUser):
to convert into enums, simply use the enum's c'tor

--> ```
CodeOwnerMetadataTypes('personalName') is CodeOwnerMetadataTypes(CodeOwnerMetadataTypes.PERSONAL_NAME)
```

also, by convention (in this repository), use singular for enum-type-names, please

2022-04-01 10:58 UTC, ccwienk commented on github/codeowners.py
> +    codeowner: CodeOwner,
not needed, i think

2022-04-05 14:21 UTC, closed without merging

2022-04-07 12:59 UTC, zkdev commented
https://github.com/gardener/cc-utils/pull/710