add oci platform filter
gardener/cc-utils pull request #753
Opened 2022-09-19 07:43 UTC by jschicktanz

**What this PR does / why we need it**:
add oci platform filter

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```other operator
- add oci platform filter
```

2022-09-20 11:31 UTC, ccwienk requested changes
generally speaking, I think I would prefer to keep most of the platform-handling code w/ the using code, and keep semantic focus of `oci` package on both model classes for (de-)serialisation of oci-manifests (+ sub-datastructures), as well as interactions w/ oci-api. Normalisation seems like a good idea (however, I am uncertain whether we should actually be strict and specify allowed platforms/architectures - this is something we do not need to restrict, and could resort to just see thos IDs as strings). As for filtering, I think this would fit better into user's code.

this will allow us to keep oci-package and using "ctt" more losely coupled

2022-09-20 11:31 UTC, ccwienk commented on oci/platform.py
> +    def contains_value(cls, value: str):
rather overwrite __contains__
as an (more pythonic) alternative, one could resort to leveraging enum.Enum's autogenerated initialiser's semantics

-> `OperatingSystem('does-not-exist')` will raise `ValueError`

2022-09-20 11:31 UTC, ccwienk commented on oci/platform.py
> +    def contains_value(cls, value: str):
ditto

2022-09-20 11:31 UTC, ccwienk commented on oci/platform.py
> +        matchers = []
nit: use list-comprehension

2022-09-20 11:31 UTC, ccwienk commented on oci/platform.py
> +        splitted = platform_expr.split('/')
nit: split, split, split

2022-09-20 11:31 UTC, ccwienk commented on oci/platform.py
> +        if len(splitted) < 2 or len(splitted) > 3:
rather use separate if-clauses for both variants - or at least output actual length in error-msg to make debugging easier

2022-09-20 11:31 UTC, ccwienk commented on oci/platform.py
> +        if len(splitted) < 2 or len(splitted) > 3:
you might want to consider using structural pattern matching (https://peps.python.org/pep-0622/)

2022-09-20 11:31 UTC, ccwienk commented on oci/platform.py
> +        if architecture != '*' and not Architecture.contains_value(architecture):
as mentioned above: simply use Archecture(value) and let ValueError propagate

2022-09-20 11:31 UTC, ccwienk commented on oci/platform.py
> +    def _match(m: dict, p: om.OciPlatform) -> bool:
there is __eq__ for that

2022-09-22 08:35 UTC, jschicktanz commented
coding was moved to https://github.com/gardener/cnudie-transport-tool/pull/488

2022-09-22 08:35 UTC, closed without merging