Enhance service binding client
gardener/cc-utils pull request #812
Opened 2023-02-15 15:15 UTC by dimityrmirchev

**What this PR does / why we need it**:
This PR adds:
 - additional function called `get_service_binding` to the SBClient
 - additional fields `created_at` and `updated_at` to be returned when getting a service binding

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
/cc @MartinWeindel
 
**Release note**:

```other operator
NONE
```

2023-02-22 14:41 UTC, ccwienk requested changes
some codestyle-nits, otherwise looks fine

2023-02-22 14:41 UTC, ccwienk commented on cfg_mgmt/btp_service_binding.py
> +    def __response_json_to_sb_detailed_info(self, resp_json) -> ServiceBindingDetailedInfo:
codestyle: "private" methods/functions should be marked w/ a single underscore. double-underscores are typically "reserved" for python-internals or -contracts 

consider using `dacite.from_dict` for deserialising `dict` -> `dataclass`

btw, using `dacite.config.Config`'s typehooks, you might even automatically deserialise timestamp-strings into `datetime.datetime` objects (if this is helpful/desirable), like so:


```
dacite.from_dict(
  data=resp_json,
  data_class=ServiceBindingDetailedInfo,
  config=dacite.config.Config(
    type_hooks={
     datetime.datetime: dateutil.parser.isoparse, # prefer dateutil.parser over python-default as the latter is buggy
   }
)
```

(for this to work, you would have to change the typehints for updated_at, created_at)

2023-02-22 14:41 UTC, ccwienk commented on cfg_mgmt/btp_service_binding.py
> +        return ServiceBindingDetailedInfo(id=id, name=name, service_instance_id=instance_id,
codestyle: we prefer to have one argument per line

2023-02-23 11:25 UTC, dimityrmirchev commented
Thanks for the feedback, @ccwienk! I made the suggested changes. PTAL

2023-02-24 11:21 UTC, ccwienk approved these changes

2023-02-25 08:56 UTC, merged